# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('last_watered', models.DateTimeField(default=django.utils.timezone.now)),
                ('water_period', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
